### ISSUE TITLE
When I execute the 'python train_stage1.py' directive, I find a problem

### ISSUE THREAD

**Issue by Martin-top** [hobincar/RecNet#1]
Hi.  Your work is very good, thank you very much for releasing your code.
However, when I was running the 'python train_stage1.py' instruction, I found a problem and I hope you can help me solve it.
Thank you very much.

----------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "train_stage1.py", line 164, in <module>
    main()
  File "train_stage1.py", line 157, in main
    best_model = load_checkpoint(model, best_ckpt_fpath)
  File "/home/test/RecNet/RecNet/utils.py", line 242, in load_checkpoint
    checkpoint = torch.load(ckpt_fpath)
  File "/home/test/RecNet/RecNet/.env/local/lib/python2.7/site-packages/torch/serialization.py", line 368, in load
    return _load(f, map_location, pickle_module)
  File "/home/test/RecNet/RecNet/.env/local/lib/python2.7/site-packages/torch/serialization.py", line 517, in _load
    _check_seekable(f)
  File "/home/test/RecNet/RecNet/.env/local/lib/python2.7/site-packages/torch/serialization.py", line 189, in _check_seekable
    raise_err_msg(["seek", "tell"], e)
  File "/home/test/RecNet/RecNet/.env/local/lib/python2.7/site-packages/torch/serialization.py", line 182, in raise_err_msg
    raise type(e)(msg)
AttributeError: 'NoneType' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.

**Comment by hobincar** [comment]
It seems that there was an error at the `try` block, but the full error message is not shown. I just removed the `try` block, as I think it is not that important functionality. So, can you run your code again and show me the error message?

**Comment by Martin-top** [comment]
First of all, thank you very much for helping me solve the above problem. When I made the modification as you suggested, another problem occurred after running 'python train_stage1.py 'again. I searched the Internet for many solutions, but none of them solved the problem. So again, I hope you can help me solve this problem.

Thank you very much.
---------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "train_stage1.py", line 156, in <module>
    main()
  File "train_stage1.py", line 127, in main
    C.reg_lambda, C.recon_lambda, C.gradient_clip)
  File "/home/test/RecNet/RecNet/utils.py", line 52, in train
    output, feats_recon = model(feats, captions, teacher_forcing_ratio)
  File "/home/test/RecNet/RecNet/.env/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/test/RecNet/RecNet/models/caption_generator.py", line 110, in forward
    teacher_forcing_ratio)
  File "/home/test/RecNet/RecNet/models/caption_generator.py", line 36, in forward_decoder
    output, hidden, attn_weights = self.decoder(output.view(1, -1), hidden, feats)
  File "/home/test/RecNet/RecNet/.env/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/test/RecNet/RecNet/models/decoder.py", line 53, in forward
    feats, attn_weights = self.attention(last_hidden, feats)
  File "/home/test/RecNet/RecNet/.env/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/test/RecNet/RecNet/models/temporal_attention.py", line 20, in forward
    Uv = self.U(feats)
  File "/home/test/RecNet/RecNet/.env/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/test/RecNet/RecNet/.env/local/lib/python2.7/site-packages/torch/nn/modules/linear.py", line 67, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/test/RecNet/RecNet/.env/local/lib/python2.7/site-packages/torch/nn/functional.py", line 1354, in linear
    output = input.matmul(weight.t())
RuntimeError: size mismatch, m1: [5600 x 25088], m2: [1536 x 256] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:266

**Comment by hobincar** [comment]
I think the shape of the features is not the same as I expected. Can you check the shape of `feats` at `models/temporal_attention.py`? I think the shape of the `feats` tensor should be `(200, 28, 1536)` (where the `200` is the batch size, `28` is the number of sampled frames, and `1536` is the feature dimension).

FYI, if you wrap the error message with backticks (```), it is more readable, like below

```
Traceback (most recent call last):
  File "train_stage1.py", line 156, in <module>
    main()
  File "train_stage1.py", line 127, in main
    C.reg_lambda, C.recon_lambda, C.gradient_clip)
  File "/home/test/RecNet/RecNet/utils.py", line 52, in train
    output, feats_recon = model(feats, captions, teacher_forcing_ratio)
...
```

**Comment by Martin-top** [comment]
I'm sorry, I can't understand you very well.I looked at the `models/temporal_attention.py` file, but all I saw were the parameters that called each other, not the actual values that were set.
For example:


```
import torch
import torch.nn as nn
import torch.nn.functional as F

class TemporalAttention(nn.Module):
    def __init__(self, hidden_size, feat_size, bottleneck_size):
        super(TemporalAttention, self).__init__()
        self.hidden_size = hidden_size
        self.feat_size = feat_size
        self.bottleneck_size = bottleneck_size

        self.W = nn.Linear(self.hidden_size, self.bottleneck_size, bias=False)
        self.U = nn.Linear(self.feat_size, self.bottleneck_size, bias=False)
        self.b = nn.Parameter(torch.ones(self.bottleneck_size), requires_grad=True)
        self.w = nn.Linear(self.bottleneck_size, 1, bias=False)

    def forward(self, hidden, feats):
        Wh = self.W(hidden)
        Uv = self.U(feats)
        Wh = Wh.unsqueeze(1).expand_as(Uv)
        energies = self.w(torch.tanh(Wh + Uv + self.b))
        weights = F.softmax(energies, dim=1)

        weighted_feats = feats * weights.expand_as(feats)
        attn_feats = weighted_feats.sum(dim=1)
        return attn_feats, weights

```

**Comment by Martin-top** [comment]
Can you provide me with your `msvd_inceptionv4.hdf5` file?I was wondering if there was a problem with my extracted `msvd_inceptionv4.hdf5` file.

**Comment by hobincar** [comment]
What I meant was, check the dimension of `feats` so that it is `(200, 28, 1536)`.

You can download the hdf5 file of MSVD [here](https://drive.google.com/open?id=15KAUejvD5Jbf7qlNPjmdsfGp5qbmkKqe).
