### ISSUE TITLE
How to solve the problem of size mismatch?

### ISSUE THREAD

**Issue by q-rong** [hobincar/RecNet#10]
Hi,
Thank you very much for your help, I successfully obtained `MSVD_C3D.hdf5`.

When I replaced `MSVD_InnceptionV4.hdf5` with `MSVD_C3D.hdf5` in `RecNet` and ran `python train.py-c configs.train_stage1`, I had a size mismatch error.

`RuntimeError: size mismatch, m1: [5600 x 4096], m2: [1536 x 256] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:266`

I don't know how to adjust the size, can you help me solve the problem?

Specific error contents are as follows:
```
Epoch 1

[TRAIN]
Traceback (most recent call last):
  File "train.py", line 166, in <module>
    main()
  File "train.py", line 137, in main
    C.reg_lambda, C.recon_lambda, C.gradient_clip)
  File "/home/RecNet/utils.py", line 52, in train
    output, feats_recon = model(feats, captions, teacher_forcing_ratio)
  File "/home/RecNet/.env/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/RecNet/models/caption_generator.py", line 110, in forward
    teacher_forcing_ratio)
  File "/home/RecNet/models/caption_generator.py", line 36, in forward_decoder
    output, hidden, attn_weights = self.decoder(output.view(1, -1), hidden, feats)
  File "/home/RecNet/.env/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/RecNet/models/decoder.py", line 53, in forward
    feats, attn_weights = self.attention(last_hidden, feats)
  File "/home/RecNet/.env/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/RecNet/models/temporal_attention.py", line 20, in forward
    Uv = self.U(feats)
  File "/home/RecNet/.env/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/RecNet/.env/local/lib/python2.7/site-packages/torch/nn/modules/linear.py", line 67, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/RecNet/.env/local/lib/python2.7/site-packages/torch/nn/functional.py", line 1354, in linear
    output = input.matmul(weight.t())
RuntimeError: size mismatch, m1: [5600 x 4096], m2: [1536 x 256] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:266



```

**Comment by hobincar** [comment]
Hi,

I think that's because the sizes of the InceptionV4 (`1536`) and C3D (`4096`) features are different. You can add a few lines in [here](https://github.com/hobincar/RecNet/blob/master/configs/train_stage1.py#L5-L12), as follows

```
class FeatureConfig:
    models = [ "MSVD_InceptionV4" ]
    size = 0
    for model in models:
        if 'InceptionV4' in model:
            size += 1536
        elif 'C3D' in model:
            size += 4096
        else:
            raise NotImplementedError("Unknown model: {}".format(model))
```

**Comment by q-rong** [comment]
Thank you very much for your help.

When I modified it according to your suggestion, I encountered a new problem. I tried to fix it, but I felt that my ability could not solve the problem.

`RuntimeError: The size of tensor a (4096) must match the size of tensor b (1536) at non-singleton dimension 1`

Specific error contents are as follows:
```
Epoch 1

[TRAIN]
Traceback (most recent call last):
  File "train.py", line 166, in <module>
    main()
  File "train.py", line 137, in main
    C.reg_lambda, C.recon_lambda, C.gradient_clip)
  File "/home/RecNet/utils.py", line 59, in train
    losses.global_reconstruction_loss(feats, feats_recon, keep_mask=(captions != PAD_idx))
  File "/home/RecNet/losses.py", line 24, in global_reconstruction_loss
    l2_loss = F.mse_loss(x, x_recon)
  File "/home/RecNet/.env/local/lib/python2.7/site-packages/torch/nn/functional.py", line 2151, in mse_loss
    ret = (input - target) ** 2
RuntimeError: The size of tensor a (4096) must match the size of tensor b (1536) at non-singleton dimension 1

```

**Comment by hobincar** [comment]
First of all, it seems that your code is not the newest, as I modified the codes so that the reconstructor is not used in the first stage of training. If you get the latest code, the problem will be fixed.

Second, you should have changed [this line for a global reconstructor](https://github.com/hobincar/RecNet/blob/master/configs/train_stage2.py#L77) or [this line for a local reconstructor](https://github.com/hobincar/RecNet/blob/master/configs/train_stage2.py#L86), which seems to be better to be just set to match the dimension of features we use. I'll fix it right away.

**Comment by q-rong** [comment]
Thank you for your help. This problem has been solved.
