### ISSUE TITLE
error in the code

### ISSUE THREAD

**Issue by Savitha2018** [hobincar/RecNet#14]

**Comment by Savitha2018** [comment]
[Epoch #1] loss: 4.703 = (CE: 4.703) + (Ent: 0.0 * 2953.708) + (Rec: 0.0 * 0.000): 100% 244/244 [1:48:44<00:00, 25.80s/it]
train loss: 5.829274394473091 (CE 5.829274394473091 + E 2903.751967133069 + REC 0.0)
Traceback (most recent call last):
  File "train.py", line 165, in <module>
    main()
  File "train.py", line 142, in main
    val_scores, _, _ = score(model, val_iter)
  File "/content/drive/My Drive/RecNet/utils.py", line 174, in score
    scores = calc_scores(refs, hypos)
  File "/content/drive/My Drive/RecNet/utils.py", line 192, in calc_scores
    score, scores = scorer.compute_score(ref, hypo)
  File "/content/drive/My Drive/RecNet/pycocoevalcap/bleu/bleu.py", line 26, in compute_score
    bleu_scorer += (hypo[0], ref)
  File "/content/drive/My Drive/RecNet/pycocoevalcap/bleu/bleu_scorer.py", line 166, in __iadd__
    self.cook_append(other[0], other[1])
  File "/content/drive/My Drive/RecNet/pycocoevalcap/bleu/bleu_scorer.py", line 115, in cook_append
    cooked_test = cook_test(test, self.crefs[-1])
TypeError: cook_test() missing 1 required positional argument: 'refmaxcounts'

I have run this code in google colab in python3 1 epoch has done
after that i am getting this error
how to solve it
i need the model ckpt file 
how to save it
pls help
thanks in advance

**Comment by hobincar** [comment]
Hi,

You should use python 2.7, not 3. The evaluation code which I got from [here](https://github.com/tylin/coco-caption) requires us to use python 2.7.
