### ISSUE TITLE
why this error comes ?

### ISSUE THREAD

**Issue by Savitha2018** [hobincar/RecNet#15]
Traceback (most recent call last):
  File "train.py", line 10, in <module>
    from eval import evaluate
  File "/content/drive/My Drive/MSVDRecnet/eval.py", line 7, in <module>
    from coco_caption.pycocoevalcap.eval import COCOEvalCap
  File "/content/drive/My Drive/MSVDRecnet/coco_caption/pycocoevalcap/eval.py", line 3, in <module>
    from coco_caption.pycocoevalcap.bleu.bleu import Bleu
  File "/content/drive/My Drive/MSVDRecnet/coco_caption/pycocoevalcap/bleu/bleu.py", line 11, in <module>
    from coco_caption.pycocoevalcap.bleu.bleu_scorer import BleuScorer
  File "/content/drive/My Drive/MSVDRecnet/coco_caption/pycocoevalcap/bleu/bleu_scorer.py", line 60
    def cook_test(test, (reflen, refmaxcounts), eff=None, n=4):
                        ^
SyntaxError: invalid syntax

how to solve this error 
how to resolve it

**Comment by hobincar** [comment]
I think you are using [the legacy codes](https://github.com/hobincar/reconstruction-network-for-video-captioning), which I don't maintain anymore. Please use codes in this repo.
