### ISSUE TITLE
error in creating the trained model

### ISSUE THREAD

**Issue by Savitha2018** [hobincar/RecNet#16]
[Epoch #1] loss: 4.706 = (CE: 4.706) + (Ent: 0.0 * 2941.608) + (Rec: 0.0 * 0.000): 100%|██████████| 244/244 [06:07<00:00,  1.50s/it]
train loss: 5.83436998383 (CE 5.83436998383 + E 2879.78789683 + REC 0.0)
Traceback (most recent call last):
  File "train.py", line 165, in <module>
    main()
  File "train.py", line 142, in main
    val_scores = evaluate(val_iter, model, model.vocab)
  File "/content/drive/My Drive/RecNet/utils.py", line 200, in evaluate
    scores = score(vid2pred, vid2GTs)
  File "/content/drive/My Drive/RecNet/utils.py", line 169, in score
    scores = calc_scores(refs, hypos)
  File "/content/drive/My Drive/RecNet/utils.py", line 188, in calc_scores
    score, scores = scorer.compute_score(ref, hypo)
  File "/content/drive/My Drive/RecNet/pycocoevalcap/bleu/bleu.py", line 28, in compute_score
    bleu_scorer += (hypo[0], ref)
  File "/content/drive/My Drive/RecNet/pycocoevalcap/bleu/bleu_scorer.py", line 166, in __iadd__
    self.cook_append(other[0], other[1])
  File "/content/drive/My Drive/RecNet/pycocoevalcap/bleu/bleu_scorer.py", line 115, in cook_append
    cooked_test = cook_test(test, self.crefs[-1])
TypeError: cook_test() takes at least 3 arguments (2 given)
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/local/lib/python2.7/dist-packages/tensorboardX/event_file_writer.py", line 208, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'moves'

how to solve this error

**Comment by hobincar** [comment]
I think you are using [the legacy codes](https://github.com/hobincar/reconstruction-network-for-video-captioning), which I don't maintain anymore. Please use codes in this repo.
