### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'append'

### ISSUE THREAD

**Issue by Savitha2018** [hobincar/RecNet#17]
MODEL ID: RecNet | MSVD tc-30 mc-5 sp-uniform | ENC InceptionV4 sm-28 | DEC GRU-1 at-128 dr-0.5-0.5 tf-1.0 lr-1e-05-wd-1e-05 op-amsgrad | REC-local LSTM lr-1e-06-wd-1e-05 op-adam at-128 | EMB 468 dr-0.5 sc-1 | bs-100 | cp-50.0 | 191123-12:47:47
DEBUG MODE: OFF
#vocabs: 4190 (13377), #words: 592193 (606709). Trim words which appear less than 5 times.
/usr/local/lib/python2.7/dist-packages/torch/nn/modules/rnn.py:51: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.5 and num_layers=1
  "num_layers={}".format(dropout, num_layers))
Traceback (most recent call last):
  File "train.py", line 427, in <module>
    main()
  File "train.py", line 241, in main
    for iteration, batch in enumerate(train_data_loader, 1):
  File "/content/drive/My Drive/RecNet_Only_MSVD/utils.py", line 7, in cycle
    for x in iterable:
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/usr/local/lib/python2.7/dist-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/drive/My Drive/RecNet_Only_MSVD/dataset/MSVD.py", line 228, in __getitem__
    video = self.transform_frame(video)
  File "/usr/local/lib/python2.7/dist-packages/torchvision/transforms/transforms.py", line 70, in __call__
    img = t(img)
  File "/content/drive/My Drive/RecNet_Only_MSVD/dataset/transform.py", line 62, in __call__
    frames.append(np.zeros_like(frames[0]))
AttributeError: 'numpy.ndarray' object has no attribute 'append'

how to solve this error

**Comment by hobincar** [comment]
I think you are using [the legacy codes](https://github.com/hobincar/reconstruction-network-for-video-captioning), which I don't maintain anymore. Please use codes in this repo.
